name: "[dispatch] sync ci all"

on:
  workflow_dispatch:

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  sync_all:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        target: ['core/python-core', 'core/api', 'core/console', 'core/console-api', 'core/python-service', 'tools/spacectl', 'doc/api-doc', 'doc/docs', ' doc/marketplace-assets']
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      
      - name: set git user
        run : git config --global user.email admin@cloudforet.io
        
      - name: set python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: install requirements
        run: pip install -r requirements.txt
        
      - name: set PAT_TOKEN env
        run: echo "PAT_TOKEN=$(echo ${{ secrets.PAT_TOKEN }})" >> $GITHUB_ENV
        
      - name: deploy
        run: |
          python src/main.py --dest ${{ matrix.target }} --type topic

  notify_to_slack:
    needs: sync_all
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
