name: "[dispatch] tmp daily build all core services"

on:
  workflow_dispatch:

env:
  BRANCH: ${{ github.event.inputs.branch }}
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  core_python_service:
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        target: ['identity', 'secret', 'repository', 'plugin', 'config', 'inventory', 'monitoring', 'statistics', 'cost-analysis', 'notification', 'board', 'file-manager', 'dashboard', 'console-api-v2', 'supervisor']
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: task
        uses: benc-uk/workflow-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: cloudforet-io/${{ matrix.target }}
          workflow: dispatch_daily_build.yaml

  notify_to_slack:
    needs: core_python_service
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.15.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
